services:
  frontend:
    image: suhaskm23/matchpoint-frontend:latest
    build:
      context: ./MatchPointFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./MatchPointFrontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - matchpoint-network
    restart: unless-stopped

  backend:
    image: suhaskm23/matchpoint-backend:latest
    build:
      context: ./MatchPointBackend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_SQL_SERVER=match-point.database.windows.net
      - AZURE_SQL_DB=MatchPoint
      - AZURE_SQL_USER=matchpoint
      - AZURE_SQL_PASSWORD=Abc@12345
      - AWS_ACCESS_KEY_ID=AKIA2CCC2FMG2MHLD5TT
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=match-point
    volumes:
      - ./MatchPointBackend:/app
    networks:
      - matchpoint-network
    restart: unless-stopped
  
networks:
  matchpoint-network:
    driver: bridge

volumes:
  node_modules: