services:
  frontend:
    image: suhaskm23/matchpoint-frontend:latest
    build:
      context: ./MatchPointFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./MatchPointFrontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - matchpoint-network
    restart: unless-stopped

  backend:
    image: suhaskm23/matchpoint-backend:latest
    build:
      context: ./MatchPointBackend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./MatchPointBackend:/app
    networks:
      - matchpoint-network
    restart: unless-stopped
  
networks:
  matchpoint-network:
    driver: bridge

volumes:
  node_modules: